### ISSUE TITLE
Auto-populate The Event Calendar from EPFL memento / actu

### ISSUE THREAD

**Issue by loichu** [epfl-sti/wordpress.plugin.memento#1]
We have to be able to add an event of memento in the plugin "the event calendar".

* If we put the correct shortcode in the event, it's transformed in text in DB
* If we remove the shortcode we're able to edit the event by hand

**Comment by loichu** [comment]
The fields needed to import are:
* Start date
* End date
* Title
* Link
* Location
* Description

**Comment by ponsfrilus** [comment]
Not needed anymore
